"use strict";
/**
 * Copyright 2021 Colin Doig.  Distributed under the MIT license.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateRelationStatus = exports.VendorDetails = exports.VendorAccessTokenInfo = exports.UpdateApplicationSubscriptionResponse = exports.UpdateApplicationSubscriptionRequest = exports.TransferResponse = exports.TransferFundsRequest = exports.TokenRequest = exports.SubscriptionTokenInfo = exports.SubscriptionOptions = exports.SubscriptionHistory = exports.StatementLegacyData = exports.StatementItem = exports.RevokeAccessToWebAppResponse = exports.RevokeAccessToWebAppRequest = exports.ListCurrencyRatesResponse = exports.ListCurrencyRatesRequest = exports.ListAuthorizedWebAppsResponse = exports.ListApplicationSubscriptionTokensResponse = exports.ListApplicationSubscriptionTokensRequest = exports.ListAccountSubscriptionTokensResponse = exports.IsAccountSubscribedToWebAppResponse = exports.IsAccountSubscribedToWebAppRequest = exports.GetVendorClientIdResponse = exports.GetVendorDetailsRequest = exports.GetDeveloperAppKeysResponse = exports.GetAuthorisationCodeRequest = exports.GetApplicationSubscriptionTokenResponse = exports.GetApplicationSubscriptionTokenRequest = exports.GetApplicationSubscriptionHistoryResponse = exports.GetApplicationSubscriptionHistoryRequest = exports.GetAffiliateRelationResponse = exports.GetAffiliateRelationRequest = exports.GetAccountStatementRequest = exports.GetAccountFundsRequest = exports.DeveloperAppVersion = exports.DeveloperApp = exports.CurrencyRate = exports.CreateDeveloperAppKeysRequest = exports.CancelApplicationSubscriptionResponse = exports.CancelApplicationSubscriptionRequest = exports.AuthorisationResponse = exports.ApplicationSubscription = exports.AffiliateRelation = exports.ActivateApplicationSubscriptionResponse = exports.ActivateApplicationSubscriptionRequest = exports.AccountSubscription = exports.AccountStatementReport = exports.AccountFundsResponse = exports.AccountDetailsResponse = void 0;
exports.ListExposureLimitsForMarketGroupsRequest = exports.ListEventTypesResponse = exports.ListEventTypesRequest = exports.ListEventsResponse = exports.ListEventsRequest = exports.ListCurrentOrdersRequest = exports.ListCountriesResponse = exports.ListCountriesRequest = exports.ListCompetitionsResponse = exports.ListCompetitionsRequest = exports.ListClearedOrdersRequest = exports.LimitOrder = exports.LimitOnCloseOrder = exports.LimitBreachAction = exports.KeyLineSelection = exports.KeyLineDescription = exports.ItemDescription = exports.GetExposureReuseEnabledEventsResponse = exports.ExposureLimitsForMarketGroups = exports.ExposureLimit = exports.ExchangePrices = exports.ExBestOffersOverrides = exports.EventTypeResult = exports.EventType = exports.EventResult = exports.Event = exports.CurrentOrderSummaryReport = exports.CurrentOrderSummary = exports.CountryCodeResult = exports.CompetitionResult = exports.Competition = exports.ClearedOrderSummaryReport = exports.ClearedOrderSummary = exports.CancelOrdersRequest = exports.CancelInstructionReport = exports.CancelInstruction = exports.CancelExecutionReport = exports.AddExposureReuseEnabledEventsResponse = exports.AddExposureReuseEnabledEventsRequest = exports.ActionPerformed = exports.HeartbeatRequest = exports.HeartbeatReport = exports.TimeRange = exports.Wallet = exports.TokenType = exports.SubscriptionStatus = exports.Status = exports.ItemClass = exports.IncludeItem = exports.GrantType = void 0;
exports.ReplaceOrdersRequest = exports.ReplaceInstructionReport = exports.ReplaceInstruction = exports.ReplaceExecutionReport = exports.RemoveExposureReuseEnabledEventsResponse = exports.RemoveExposureReuseEnabledEventsRequest = exports.RemoveExposureLimitForMarketGroupResponse = exports.RemoveExposureLimitForMarketGroupRequest = exports.RemoveDefaultExposureLimitForMarketGroupsResponse = exports.RemoveDefaultExposureLimitForMarketGroupsRequest = exports.PriceSize = exports.PriceProjection = exports.PlaceOrdersRequest = exports.PriceLadderDescription = exports.PlaceInstructionReport = exports.PlaceInstruction = exports.PlaceExecutionReport = exports.Order = exports.Matches = exports.Match = exports.MarketVersion = exports.MarketTypeResult = exports.MarketState = exports.MarketRates = exports.MarketProfitAndLoss = exports.MarketOnCloseOrder = exports.MarketLineRangeInfo = exports.MarketLicence = exports.MarketGroupId = exports.MarketGroupExposureLimit = exports.MarketGroup = exports.MarketFilter = exports.MarketDescription = exports.MarketCatalogue = exports.MarketBook = exports.ListVenuesResponse = exports.ListVenuesRequest = exports.ListTimeRangesResponse = exports.ListTimeRangesRequest = exports.ListRunnerBookResponse = exports.ListRunnerBookRequest = exports.ListMarketTypesResponse = exports.ListMarketTypesRequest = exports.ListMarketProfitAndLossResponse = exports.ListMarketProfitAndLossRequest = exports.ListMarketCatalogueResponse = exports.ListMarketCatalogueRequest = exports.ListMarketBookResponse = exports.ListMarketBookRequest = exports.ListExposureLimitsForMarketGroupsResponse = void 0;
exports.LoginEndPoint = exports.ExchangeApi = exports.TimeInForce = exports.TimeGranularity = exports.SortDir = exports.Side = exports.RunnerStatus = exports.RollupModel = exports.PriceLadderType = exports.PriceData = exports.PersistenceType = exports.OrderType = exports.OrderStatus = exports.OrderProjection = exports.OrderBy = exports.MatchProjection = exports.MarketStatus = exports.MarketSort = exports.MarketProjection = exports.MarketGroupType = exports.MarketBettingType = exports.LimitBreachActionType = exports.InstructionReportStatus = exports.InstructionReportErrorCode = exports.GroupBy = exports.ExecutionReportStatus = exports.ExecutionReportErrorCode = exports.BetTargetType = exports.BetStatus = exports.VenueResult = exports.UpdateOrdersRequest = exports.UpdateInstructionReport = exports.UpdateInstruction = exports.UpdateExecutionReport = exports.UnblockMarketGroupResponse = exports.UnblockMarketGroupRequest = exports.TimeRangeResult = exports.StartingPrices = exports.SetExposureLimitForMarketGroupResponse = exports.SetExposureLimitForMarketGroupRequest = exports.SetDefaultExposureLimitForMarketGroupsResponse = exports.SetDefaultExposureLimitForMarketGroupsRequest = exports.RunnerProfitAndLoss = exports.RunnerId = exports.RunnerCatalog = exports.Runner = void 0;
var AccountDetailsResponse_1 = require("./account/AccountDetailsResponse");
Object.defineProperty(exports, "AccountDetailsResponse", { enumerable: true, get: function () { return AccountDetailsResponse_1.default; } });
var AccountFundsResponse_1 = require("./account/AccountFundsResponse");
Object.defineProperty(exports, "AccountFundsResponse", { enumerable: true, get: function () { return AccountFundsResponse_1.default; } });
var AccountStatementReport_1 = require("./account/AccountStatementReport");
Object.defineProperty(exports, "AccountStatementReport", { enumerable: true, get: function () { return AccountStatementReport_1.default; } });
var AccountSubscription_1 = require("./account/AccountSubscription");
Object.defineProperty(exports, "AccountSubscription", { enumerable: true, get: function () { return AccountSubscription_1.default; } });
var ActivateApplicationSubscriptionRequest_1 = require("./account/ActivateApplicationSubscriptionRequest");
Object.defineProperty(exports, "ActivateApplicationSubscriptionRequest", { enumerable: true, get: function () { return ActivateApplicationSubscriptionRequest_1.default; } });
var ActivateApplicationSubscriptionResponse_1 = require("./account/ActivateApplicationSubscriptionResponse");
Object.defineProperty(exports, "ActivateApplicationSubscriptionResponse", { enumerable: true, get: function () { return ActivateApplicationSubscriptionResponse_1.default; } });
var AffiliateRelation_1 = require("./account/AffiliateRelation");
Object.defineProperty(exports, "AffiliateRelation", { enumerable: true, get: function () { return AffiliateRelation_1.default; } });
var ApplicationSubscription_1 = require("./account/ApplicationSubscription");
Object.defineProperty(exports, "ApplicationSubscription", { enumerable: true, get: function () { return ApplicationSubscription_1.default; } });
var AuthorisationResponse_1 = require("./account/AuthorisationResponse");
Object.defineProperty(exports, "AuthorisationResponse", { enumerable: true, get: function () { return AuthorisationResponse_1.default; } });
var CancelApplicationSubscriptionRequest_1 = require("./account/CancelApplicationSubscriptionRequest");
Object.defineProperty(exports, "CancelApplicationSubscriptionRequest", { enumerable: true, get: function () { return CancelApplicationSubscriptionRequest_1.default; } });
var CancelApplicationSubscriptionResponse_1 = require("./account/CancelApplicationSubscriptionResponse");
Object.defineProperty(exports, "CancelApplicationSubscriptionResponse", { enumerable: true, get: function () { return CancelApplicationSubscriptionResponse_1.default; } });
var CreateDeveloperAppKeysRequest_1 = require("./account/CreateDeveloperAppKeysRequest");
Object.defineProperty(exports, "CreateDeveloperAppKeysRequest", { enumerable: true, get: function () { return CreateDeveloperAppKeysRequest_1.default; } });
var CurrencyRate_1 = require("./account/CurrencyRate");
Object.defineProperty(exports, "CurrencyRate", { enumerable: true, get: function () { return CurrencyRate_1.default; } });
var DeveloperApp_1 = require("./account/DeveloperApp");
Object.defineProperty(exports, "DeveloperApp", { enumerable: true, get: function () { return DeveloperApp_1.default; } });
var DeveloperAppVersion_1 = require("./account/DeveloperAppVersion");
Object.defineProperty(exports, "DeveloperAppVersion", { enumerable: true, get: function () { return DeveloperAppVersion_1.default; } });
var GetAccountFundsRequest_1 = require("./account/GetAccountFundsRequest");
Object.defineProperty(exports, "GetAccountFundsRequest", { enumerable: true, get: function () { return GetAccountFundsRequest_1.default; } });
var GetAccountStatementRequest_1 = require("./account/GetAccountStatementRequest");
Object.defineProperty(exports, "GetAccountStatementRequest", { enumerable: true, get: function () { return GetAccountStatementRequest_1.default; } });
var GetAffiliateRelationRequest_1 = require("./account/GetAffiliateRelationRequest");
Object.defineProperty(exports, "GetAffiliateRelationRequest", { enumerable: true, get: function () { return GetAffiliateRelationRequest_1.default; } });
var GetAffiliateRelationResponse_1 = require("./account/GetAffiliateRelationResponse");
Object.defineProperty(exports, "GetAffiliateRelationResponse", { enumerable: true, get: function () { return GetAffiliateRelationResponse_1.default; } });
var GetApplicationSubscriptionHistoryRequest_1 = require("./account/GetApplicationSubscriptionHistoryRequest");
Object.defineProperty(exports, "GetApplicationSubscriptionHistoryRequest", { enumerable: true, get: function () { return GetApplicationSubscriptionHistoryRequest_1.default; } });
var GetApplicationSubscriptionHistoryResponse_1 = require("./account/GetApplicationSubscriptionHistoryResponse");
Object.defineProperty(exports, "GetApplicationSubscriptionHistoryResponse", { enumerable: true, get: function () { return GetApplicationSubscriptionHistoryResponse_1.default; } });
var GetApplicationSubscriptionTokenRequest_1 = require("./account/GetApplicationSubscriptionTokenRequest");
Object.defineProperty(exports, "GetApplicationSubscriptionTokenRequest", { enumerable: true, get: function () { return GetApplicationSubscriptionTokenRequest_1.default; } });
var GetApplicationSubscriptionTokenResponse_1 = require("./account/GetApplicationSubscriptionTokenResponse");
Object.defineProperty(exports, "GetApplicationSubscriptionTokenResponse", { enumerable: true, get: function () { return GetApplicationSubscriptionTokenResponse_1.default; } });
var GetAuthorisationCodeRequest_1 = require("./account/GetAuthorisationCodeRequest");
Object.defineProperty(exports, "GetAuthorisationCodeRequest", { enumerable: true, get: function () { return GetAuthorisationCodeRequest_1.default; } });
var GetDeveloperAppKeysResponse_1 = require("./account/GetDeveloperAppKeysResponse");
Object.defineProperty(exports, "GetDeveloperAppKeysResponse", { enumerable: true, get: function () { return GetDeveloperAppKeysResponse_1.default; } });
var GetVendorDetailsRequest_1 = require("./account/GetVendorDetailsRequest");
Object.defineProperty(exports, "GetVendorDetailsRequest", { enumerable: true, get: function () { return GetVendorDetailsRequest_1.default; } });
var GetVendorClientIdResponse_1 = require("./account/GetVendorClientIdResponse");
Object.defineProperty(exports, "GetVendorClientIdResponse", { enumerable: true, get: function () { return GetVendorClientIdResponse_1.default; } });
var IsAccountSubscribedToWebAppRequest_1 = require("./account/IsAccountSubscribedToWebAppRequest");
Object.defineProperty(exports, "IsAccountSubscribedToWebAppRequest", { enumerable: true, get: function () { return IsAccountSubscribedToWebAppRequest_1.default; } });
var IsAccountSubscribedToWebAppResponse_1 = require("./account/IsAccountSubscribedToWebAppResponse");
Object.defineProperty(exports, "IsAccountSubscribedToWebAppResponse", { enumerable: true, get: function () { return IsAccountSubscribedToWebAppResponse_1.default; } });
var ListAccountSubscriptionTokensResponse_1 = require("./account/ListAccountSubscriptionTokensResponse");
Object.defineProperty(exports, "ListAccountSubscriptionTokensResponse", { enumerable: true, get: function () { return ListAccountSubscriptionTokensResponse_1.default; } });
var ListApplicationSubscriptionTokensRequest_1 = require("./account/ListApplicationSubscriptionTokensRequest");
Object.defineProperty(exports, "ListApplicationSubscriptionTokensRequest", { enumerable: true, get: function () { return ListApplicationSubscriptionTokensRequest_1.default; } });
var ListApplicationSubscriptionTokensResponse_1 = require("./account/ListApplicationSubscriptionTokensResponse");
Object.defineProperty(exports, "ListApplicationSubscriptionTokensResponse", { enumerable: true, get: function () { return ListApplicationSubscriptionTokensResponse_1.default; } });
var ListAuthorizedWebAppsResponse_1 = require("./account/ListAuthorizedWebAppsResponse");
Object.defineProperty(exports, "ListAuthorizedWebAppsResponse", { enumerable: true, get: function () { return ListAuthorizedWebAppsResponse_1.default; } });
var ListCurrencyRatesRequest_1 = require("./account/ListCurrencyRatesRequest");
Object.defineProperty(exports, "ListCurrencyRatesRequest", { enumerable: true, get: function () { return ListCurrencyRatesRequest_1.default; } });
var ListCurrencyRatesResponse_1 = require("./account/ListCurrencyRatesResponse");
Object.defineProperty(exports, "ListCurrencyRatesResponse", { enumerable: true, get: function () { return ListCurrencyRatesResponse_1.default; } });
var RevokeAccessToWebAppRequest_1 = require("./account/RevokeAccessToWebAppRequest");
Object.defineProperty(exports, "RevokeAccessToWebAppRequest", { enumerable: true, get: function () { return RevokeAccessToWebAppRequest_1.default; } });
var RevokeAccessToWebAppResponse_1 = require("./account/RevokeAccessToWebAppResponse");
Object.defineProperty(exports, "RevokeAccessToWebAppResponse", { enumerable: true, get: function () { return RevokeAccessToWebAppResponse_1.default; } });
var StatementItem_1 = require("./account/StatementItem");
Object.defineProperty(exports, "StatementItem", { enumerable: true, get: function () { return StatementItem_1.default; } });
var StatementLegacyData_1 = require("./account/StatementLegacyData");
Object.defineProperty(exports, "StatementLegacyData", { enumerable: true, get: function () { return StatementLegacyData_1.default; } });
var SubscriptionHistory_1 = require("./account/SubscriptionHistory");
Object.defineProperty(exports, "SubscriptionHistory", { enumerable: true, get: function () { return SubscriptionHistory_1.default; } });
var SubscriptionOptions_1 = require("./account/SubscriptionOptions");
Object.defineProperty(exports, "SubscriptionOptions", { enumerable: true, get: function () { return SubscriptionOptions_1.default; } });
var SubscriptionTokenInfo_1 = require("./account/SubscriptionTokenInfo");
Object.defineProperty(exports, "SubscriptionTokenInfo", { enumerable: true, get: function () { return SubscriptionTokenInfo_1.default; } });
var TokenRequest_1 = require("./account/TokenRequest");
Object.defineProperty(exports, "TokenRequest", { enumerable: true, get: function () { return TokenRequest_1.default; } });
var TransferFundsRequest_1 = require("./account/TransferFundsRequest");
Object.defineProperty(exports, "TransferFundsRequest", { enumerable: true, get: function () { return TransferFundsRequest_1.default; } });
var TransferResponse_1 = require("./account/TransferResponse");
Object.defineProperty(exports, "TransferResponse", { enumerable: true, get: function () { return TransferResponse_1.default; } });
var UpdateApplicationSubscriptionRequest_1 = require("./account/UpdateApplicationSubscriptionRequest");
Object.defineProperty(exports, "UpdateApplicationSubscriptionRequest", { enumerable: true, get: function () { return UpdateApplicationSubscriptionRequest_1.default; } });
var UpdateApplicationSubscriptionResponse_1 = require("./account/UpdateApplicationSubscriptionResponse");
Object.defineProperty(exports, "UpdateApplicationSubscriptionResponse", { enumerable: true, get: function () { return UpdateApplicationSubscriptionResponse_1.default; } });
var VendorAccessTokenInfo_1 = require("./account/VendorAccessTokenInfo");
Object.defineProperty(exports, "VendorAccessTokenInfo", { enumerable: true, get: function () { return VendorAccessTokenInfo_1.default; } });
var VendorDetails_1 = require("./account/VendorDetails");
Object.defineProperty(exports, "VendorDetails", { enumerable: true, get: function () { return VendorDetails_1.default; } });
var AffiliateRelationStatus_1 = require("./account/enum/AffiliateRelationStatus");
Object.defineProperty(exports, "AffiliateRelationStatus", { enumerable: true, get: function () { return AffiliateRelationStatus_1.default; } });
var GrantType_1 = require("./account/enum/GrantType");
Object.defineProperty(exports, "GrantType", { enumerable: true, get: function () { return GrantType_1.default; } });
var IncludeItem_1 = require("./account/enum/IncludeItem");
Object.defineProperty(exports, "IncludeItem", { enumerable: true, get: function () { return IncludeItem_1.default; } });
var ItemClass_1 = require("./account/enum/ItemClass");
Object.defineProperty(exports, "ItemClass", { enumerable: true, get: function () { return ItemClass_1.default; } });
var Status_1 = require("./account/enum/Status");
Object.defineProperty(exports, "Status", { enumerable: true, get: function () { return Status_1.default; } });
var SubscriptionStatus_1 = require("./account/enum/SubscriptionStatus");
Object.defineProperty(exports, "SubscriptionStatus", { enumerable: true, get: function () { return SubscriptionStatus_1.default; } });
var TokenType_1 = require("./account/enum/TokenType");
Object.defineProperty(exports, "TokenType", { enumerable: true, get: function () { return TokenType_1.default; } });
var Wallet_1 = require("./account/enum/Wallet");
Object.defineProperty(exports, "Wallet", { enumerable: true, get: function () { return Wallet_1.default; } });
var TimeRange_1 = require("./common/TimeRange");
Object.defineProperty(exports, "TimeRange", { enumerable: true, get: function () { return TimeRange_1.default; } });
var HeartbeatReport_1 = require("./heartbeat/HeartbeatReport");
Object.defineProperty(exports, "HeartbeatReport", { enumerable: true, get: function () { return HeartbeatReport_1.default; } });
var HeartbeatRequest_1 = require("./heartbeat/HeartbeatRequest");
Object.defineProperty(exports, "HeartbeatRequest", { enumerable: true, get: function () { return HeartbeatRequest_1.default; } });
var ActionPerformed_1 = require("./heartbeat/enum/ActionPerformed");
Object.defineProperty(exports, "ActionPerformed", { enumerable: true, get: function () { return ActionPerformed_1.default; } });
var AddExposureReuseEnabledEventsRequest_1 = require("./sport/AddExposureReuseEnabledEventsRequest");
Object.defineProperty(exports, "AddExposureReuseEnabledEventsRequest", { enumerable: true, get: function () { return AddExposureReuseEnabledEventsRequest_1.default; } });
var AddExposureReuseEnabledEventsResponse_1 = require("./sport/AddExposureReuseEnabledEventsResponse");
Object.defineProperty(exports, "AddExposureReuseEnabledEventsResponse", { enumerable: true, get: function () { return AddExposureReuseEnabledEventsResponse_1.default; } });
var CancelExecutionReport_1 = require("./sport/CancelExecutionReport");
Object.defineProperty(exports, "CancelExecutionReport", { enumerable: true, get: function () { return CancelExecutionReport_1.default; } });
var CancelInstruction_1 = require("./sport/CancelInstruction");
Object.defineProperty(exports, "CancelInstruction", { enumerable: true, get: function () { return CancelInstruction_1.default; } });
var CancelInstructionReport_1 = require("./sport/CancelInstructionReport");
Object.defineProperty(exports, "CancelInstructionReport", { enumerable: true, get: function () { return CancelInstructionReport_1.default; } });
var CancelOrdersRequest_1 = require("./sport/CancelOrdersRequest");
Object.defineProperty(exports, "CancelOrdersRequest", { enumerable: true, get: function () { return CancelOrdersRequest_1.default; } });
var ClearedOrderSummary_1 = require("./sport/ClearedOrderSummary");
Object.defineProperty(exports, "ClearedOrderSummary", { enumerable: true, get: function () { return ClearedOrderSummary_1.default; } });
var ClearedOrderSummaryReport_1 = require("./sport/ClearedOrderSummaryReport");
Object.defineProperty(exports, "ClearedOrderSummaryReport", { enumerable: true, get: function () { return ClearedOrderSummaryReport_1.default; } });
var Competition_1 = require("./sport/Competition");
Object.defineProperty(exports, "Competition", { enumerable: true, get: function () { return Competition_1.default; } });
var CompetitionResult_1 = require("./sport/CompetitionResult");
Object.defineProperty(exports, "CompetitionResult", { enumerable: true, get: function () { return CompetitionResult_1.default; } });
var CountryCodeResult_1 = require("./sport/CountryCodeResult");
Object.defineProperty(exports, "CountryCodeResult", { enumerable: true, get: function () { return CountryCodeResult_1.default; } });
var CurrentOrderSummary_1 = require("./sport/CurrentOrderSummary");
Object.defineProperty(exports, "CurrentOrderSummary", { enumerable: true, get: function () { return CurrentOrderSummary_1.default; } });
var CurrentOrderSummaryReport_1 = require("./sport/CurrentOrderSummaryReport");
Object.defineProperty(exports, "CurrentOrderSummaryReport", { enumerable: true, get: function () { return CurrentOrderSummaryReport_1.default; } });
var Event_1 = require("./sport/Event");
Object.defineProperty(exports, "Event", { enumerable: true, get: function () { return Event_1.default; } });
var EventResult_1 = require("./sport/EventResult");
Object.defineProperty(exports, "EventResult", { enumerable: true, get: function () { return EventResult_1.default; } });
var EventType_1 = require("./sport/EventType");
Object.defineProperty(exports, "EventType", { enumerable: true, get: function () { return EventType_1.default; } });
var EventTypeResult_1 = require("./sport/EventTypeResult");
Object.defineProperty(exports, "EventTypeResult", { enumerable: true, get: function () { return EventTypeResult_1.default; } });
var ExBestOffersOverrides_1 = require("./sport/ExBestOffersOverrides");
Object.defineProperty(exports, "ExBestOffersOverrides", { enumerable: true, get: function () { return ExBestOffersOverrides_1.default; } });
var ExchangePrices_1 = require("./sport/ExchangePrices");
Object.defineProperty(exports, "ExchangePrices", { enumerable: true, get: function () { return ExchangePrices_1.default; } });
var ExposureLimit_1 = require("./sport/ExposureLimit");
Object.defineProperty(exports, "ExposureLimit", { enumerable: true, get: function () { return ExposureLimit_1.default; } });
var ExposureLimitsForMarketGroups_1 = require("./sport/ExposureLimitsForMarketGroups");
Object.defineProperty(exports, "ExposureLimitsForMarketGroups", { enumerable: true, get: function () { return ExposureLimitsForMarketGroups_1.default; } });
var GetExposureReuseEnabledEventsResponse_1 = require("./sport/GetExposureReuseEnabledEventsResponse");
Object.defineProperty(exports, "GetExposureReuseEnabledEventsResponse", { enumerable: true, get: function () { return GetExposureReuseEnabledEventsResponse_1.default; } });
var ItemDescription_1 = require("./sport/ItemDescription");
Object.defineProperty(exports, "ItemDescription", { enumerable: true, get: function () { return ItemDescription_1.default; } });
var KeyLineDescription_1 = require("./sport/KeyLineDescription");
Object.defineProperty(exports, "KeyLineDescription", { enumerable: true, get: function () { return KeyLineDescription_1.default; } });
var KeyLineSelection_1 = require("./sport/KeyLineSelection");
Object.defineProperty(exports, "KeyLineSelection", { enumerable: true, get: function () { return KeyLineSelection_1.default; } });
var LimitBreachAction_1 = require("./sport/LimitBreachAction");
Object.defineProperty(exports, "LimitBreachAction", { enumerable: true, get: function () { return LimitBreachAction_1.default; } });
var LimitOnCloseOrder_1 = require("./sport/LimitOnCloseOrder");
Object.defineProperty(exports, "LimitOnCloseOrder", { enumerable: true, get: function () { return LimitOnCloseOrder_1.default; } });
var LimitOrder_1 = require("./sport/LimitOrder");
Object.defineProperty(exports, "LimitOrder", { enumerable: true, get: function () { return LimitOrder_1.default; } });
var ListClearedOrdersRequest_1 = require("./sport/ListClearedOrdersRequest");
Object.defineProperty(exports, "ListClearedOrdersRequest", { enumerable: true, get: function () { return ListClearedOrdersRequest_1.default; } });
var ListCompetitionsRequest_1 = require("./sport/ListCompetitionsRequest");
Object.defineProperty(exports, "ListCompetitionsRequest", { enumerable: true, get: function () { return ListCompetitionsRequest_1.default; } });
var ListCompetitionsResponse_1 = require("./sport/ListCompetitionsResponse");
Object.defineProperty(exports, "ListCompetitionsResponse", { enumerable: true, get: function () { return ListCompetitionsResponse_1.default; } });
var ListCountriesRequest_1 = require("./sport/ListCountriesRequest");
Object.defineProperty(exports, "ListCountriesRequest", { enumerable: true, get: function () { return ListCountriesRequest_1.default; } });
var ListCountriesResponse_1 = require("./sport/ListCountriesResponse");
Object.defineProperty(exports, "ListCountriesResponse", { enumerable: true, get: function () { return ListCountriesResponse_1.default; } });
var ListCurrentOrdersRequest_1 = require("./sport/ListCurrentOrdersRequest");
Object.defineProperty(exports, "ListCurrentOrdersRequest", { enumerable: true, get: function () { return ListCurrentOrdersRequest_1.default; } });
var ListEventsRequest_1 = require("./sport/ListEventsRequest");
Object.defineProperty(exports, "ListEventsRequest", { enumerable: true, get: function () { return ListEventsRequest_1.default; } });
var ListEventsResponse_1 = require("./sport/ListEventsResponse");
Object.defineProperty(exports, "ListEventsResponse", { enumerable: true, get: function () { return ListEventsResponse_1.default; } });
var ListEventTypesRequest_1 = require("./sport/ListEventTypesRequest");
Object.defineProperty(exports, "ListEventTypesRequest", { enumerable: true, get: function () { return ListEventTypesRequest_1.default; } });
var ListEventTypesResponse_1 = require("./sport/ListEventTypesResponse");
Object.defineProperty(exports, "ListEventTypesResponse", { enumerable: true, get: function () { return ListEventTypesResponse_1.default; } });
var ListExposureLimitsForMarketGroupsRequest_1 = require("./sport/ListExposureLimitsForMarketGroupsRequest");
Object.defineProperty(exports, "ListExposureLimitsForMarketGroupsRequest", { enumerable: true, get: function () { return ListExposureLimitsForMarketGroupsRequest_1.default; } });
var ListExposureLimitsForMarketGroupsResponse_1 = require("./sport/ListExposureLimitsForMarketGroupsResponse");
Object.defineProperty(exports, "ListExposureLimitsForMarketGroupsResponse", { enumerable: true, get: function () { return ListExposureLimitsForMarketGroupsResponse_1.default; } });
var ListMarketBookRequest_1 = require("./sport/ListMarketBookRequest");
Object.defineProperty(exports, "ListMarketBookRequest", { enumerable: true, get: function () { return ListMarketBookRequest_1.default; } });
var ListMarketBookResponse_1 = require("./sport/ListMarketBookResponse");
Object.defineProperty(exports, "ListMarketBookResponse", { enumerable: true, get: function () { return ListMarketBookResponse_1.default; } });
var ListMarketCatalogueRequest_1 = require("./sport/ListMarketCatalogueRequest");
Object.defineProperty(exports, "ListMarketCatalogueRequest", { enumerable: true, get: function () { return ListMarketCatalogueRequest_1.default; } });
var ListMarketCatalogueResponse_1 = require("./sport/ListMarketCatalogueResponse");
Object.defineProperty(exports, "ListMarketCatalogueResponse", { enumerable: true, get: function () { return ListMarketCatalogueResponse_1.default; } });
var ListMarketProfitAndLossRequest_1 = require("./sport/ListMarketProfitAndLossRequest");
Object.defineProperty(exports, "ListMarketProfitAndLossRequest", { enumerable: true, get: function () { return ListMarketProfitAndLossRequest_1.default; } });
var ListMarketProfitAndLossResponse_1 = require("./sport/ListMarketProfitAndLossResponse");
Object.defineProperty(exports, "ListMarketProfitAndLossResponse", { enumerable: true, get: function () { return ListMarketProfitAndLossResponse_1.default; } });
var ListMarketTypesRequest_1 = require("./sport/ListMarketTypesRequest");
Object.defineProperty(exports, "ListMarketTypesRequest", { enumerable: true, get: function () { return ListMarketTypesRequest_1.default; } });
var ListMarketTypesResponse_1 = require("./sport/ListMarketTypesResponse");
Object.defineProperty(exports, "ListMarketTypesResponse", { enumerable: true, get: function () { return ListMarketTypesResponse_1.default; } });
var ListRunnerBookRequest_1 = require("./sport/ListRunnerBookRequest");
Object.defineProperty(exports, "ListRunnerBookRequest", { enumerable: true, get: function () { return ListRunnerBookRequest_1.default; } });
var ListRunnerBookResponse_1 = require("./sport/ListRunnerBookResponse");
Object.defineProperty(exports, "ListRunnerBookResponse", { enumerable: true, get: function () { return ListRunnerBookResponse_1.default; } });
var ListTimeRangesRequest_1 = require("./sport/ListTimeRangesRequest");
Object.defineProperty(exports, "ListTimeRangesRequest", { enumerable: true, get: function () { return ListTimeRangesRequest_1.default; } });
var ListTimeRangesResponse_1 = require("./sport/ListTimeRangesResponse");
Object.defineProperty(exports, "ListTimeRangesResponse", { enumerable: true, get: function () { return ListTimeRangesResponse_1.default; } });
var ListVenuesRequest_1 = require("./sport/ListVenuesRequest");
Object.defineProperty(exports, "ListVenuesRequest", { enumerable: true, get: function () { return ListVenuesRequest_1.default; } });
var ListVenuesResponse_1 = require("./sport/ListVenuesResponse");
Object.defineProperty(exports, "ListVenuesResponse", { enumerable: true, get: function () { return ListVenuesResponse_1.default; } });
var MarketBook_1 = require("./sport/MarketBook");
Object.defineProperty(exports, "MarketBook", { enumerable: true, get: function () { return MarketBook_1.default; } });
var MarketCatalogue_1 = require("./sport/MarketCatalogue");
Object.defineProperty(exports, "MarketCatalogue", { enumerable: true, get: function () { return MarketCatalogue_1.default; } });
var MarketDescription_1 = require("./sport/MarketDescription");
Object.defineProperty(exports, "MarketDescription", { enumerable: true, get: function () { return MarketDescription_1.default; } });
var MarketFilter_1 = require("./sport/MarketFilter");
Object.defineProperty(exports, "MarketFilter", { enumerable: true, get: function () { return MarketFilter_1.default; } });
var MarketGroup_1 = require("./sport/MarketGroup");
Object.defineProperty(exports, "MarketGroup", { enumerable: true, get: function () { return MarketGroup_1.default; } });
var MarketGroupExposureLimit_1 = require("./sport/MarketGroupExposureLimit");
Object.defineProperty(exports, "MarketGroupExposureLimit", { enumerable: true, get: function () { return MarketGroupExposureLimit_1.default; } });
var MarketGroupId_1 = require("./sport/MarketGroupId");
Object.defineProperty(exports, "MarketGroupId", { enumerable: true, get: function () { return MarketGroupId_1.default; } });
var MarketLicence_1 = require("./sport/MarketLicence");
Object.defineProperty(exports, "MarketLicence", { enumerable: true, get: function () { return MarketLicence_1.default; } });
var MarketLineRangeInfo_1 = require("./sport/MarketLineRangeInfo");
Object.defineProperty(exports, "MarketLineRangeInfo", { enumerable: true, get: function () { return MarketLineRangeInfo_1.default; } });
var MarketOnCloseOrder_1 = require("./sport/MarketOnCloseOrder");
Object.defineProperty(exports, "MarketOnCloseOrder", { enumerable: true, get: function () { return MarketOnCloseOrder_1.default; } });
var MarketProfitAndLoss_1 = require("./sport/MarketProfitAndLoss");
Object.defineProperty(exports, "MarketProfitAndLoss", { enumerable: true, get: function () { return MarketProfitAndLoss_1.default; } });
var MarketRates_1 = require("./sport/MarketRates");
Object.defineProperty(exports, "MarketRates", { enumerable: true, get: function () { return MarketRates_1.default; } });
var MarketState_1 = require("./sport/MarketState");
Object.defineProperty(exports, "MarketState", { enumerable: true, get: function () { return MarketState_1.default; } });
var MarketTypeResult_1 = require("./sport/MarketTypeResult");
Object.defineProperty(exports, "MarketTypeResult", { enumerable: true, get: function () { return MarketTypeResult_1.default; } });
var MarketVersion_1 = require("./sport/MarketVersion");
Object.defineProperty(exports, "MarketVersion", { enumerable: true, get: function () { return MarketVersion_1.default; } });
var Match_1 = require("./sport/Match");
Object.defineProperty(exports, "Match", { enumerable: true, get: function () { return Match_1.default; } });
var Matches_1 = require("./sport/Matches");
Object.defineProperty(exports, "Matches", { enumerable: true, get: function () { return Matches_1.default; } });
var Order_1 = require("./sport/Order");
Object.defineProperty(exports, "Order", { enumerable: true, get: function () { return Order_1.default; } });
var PlaceExecutionReport_1 = require("./sport/PlaceExecutionReport");
Object.defineProperty(exports, "PlaceExecutionReport", { enumerable: true, get: function () { return PlaceExecutionReport_1.default; } });
var PlaceInstruction_1 = require("./sport/PlaceInstruction");
Object.defineProperty(exports, "PlaceInstruction", { enumerable: true, get: function () { return PlaceInstruction_1.default; } });
var PlaceInstructionReport_1 = require("./sport/PlaceInstructionReport");
Object.defineProperty(exports, "PlaceInstructionReport", { enumerable: true, get: function () { return PlaceInstructionReport_1.default; } });
var PriceLadderDescription_1 = require("./sport/PriceLadderDescription");
Object.defineProperty(exports, "PriceLadderDescription", { enumerable: true, get: function () { return PriceLadderDescription_1.default; } });
var PlaceOrdersRequest_1 = require("./sport/PlaceOrdersRequest");
Object.defineProperty(exports, "PlaceOrdersRequest", { enumerable: true, get: function () { return PlaceOrdersRequest_1.default; } });
var PriceProjection_1 = require("./sport/PriceProjection");
Object.defineProperty(exports, "PriceProjection", { enumerable: true, get: function () { return PriceProjection_1.default; } });
var PriceSize_1 = require("./sport/PriceSize");
Object.defineProperty(exports, "PriceSize", { enumerable: true, get: function () { return PriceSize_1.default; } });
var RemoveDefaultExposureLimitForMarketGroupsRequest_1 = require("./sport/RemoveDefaultExposureLimitForMarketGroupsRequest");
Object.defineProperty(exports, "RemoveDefaultExposureLimitForMarketGroupsRequest", { enumerable: true, get: function () { return RemoveDefaultExposureLimitForMarketGroupsRequest_1.default; } });
var RemoveDefaultExposureLimitForMarketGroupsResponse_1 = require("./sport/RemoveDefaultExposureLimitForMarketGroupsResponse");
Object.defineProperty(exports, "RemoveDefaultExposureLimitForMarketGroupsResponse", { enumerable: true, get: function () { return RemoveDefaultExposureLimitForMarketGroupsResponse_1.default; } });
var RemoveExposureLimitForMarketGroupRequest_1 = require("./sport/RemoveExposureLimitForMarketGroupRequest");
Object.defineProperty(exports, "RemoveExposureLimitForMarketGroupRequest", { enumerable: true, get: function () { return RemoveExposureLimitForMarketGroupRequest_1.default; } });
var RemoveExposureLimitForMarketGroupResponse_1 = require("./sport/RemoveExposureLimitForMarketGroupResponse");
Object.defineProperty(exports, "RemoveExposureLimitForMarketGroupResponse", { enumerable: true, get: function () { return RemoveExposureLimitForMarketGroupResponse_1.default; } });
var RemoveExposureReuseEnabledEventsRequest_1 = require("./sport/RemoveExposureReuseEnabledEventsRequest");
Object.defineProperty(exports, "RemoveExposureReuseEnabledEventsRequest", { enumerable: true, get: function () { return RemoveExposureReuseEnabledEventsRequest_1.default; } });
var RemoveExposureReuseEnabledEventsResponse_1 = require("./sport/RemoveExposureReuseEnabledEventsResponse");
Object.defineProperty(exports, "RemoveExposureReuseEnabledEventsResponse", { enumerable: true, get: function () { return RemoveExposureReuseEnabledEventsResponse_1.default; } });
var ReplaceExecutionReport_1 = require("./sport/ReplaceExecutionReport");
Object.defineProperty(exports, "ReplaceExecutionReport", { enumerable: true, get: function () { return ReplaceExecutionReport_1.default; } });
var ReplaceInstruction_1 = require("./sport/ReplaceInstruction");
Object.defineProperty(exports, "ReplaceInstruction", { enumerable: true, get: function () { return ReplaceInstruction_1.default; } });
var ReplaceInstructionReport_1 = require("./sport/ReplaceInstructionReport");
Object.defineProperty(exports, "ReplaceInstructionReport", { enumerable: true, get: function () { return ReplaceInstructionReport_1.default; } });
var ReplaceOrdersRequest_1 = require("./sport/ReplaceOrdersRequest");
Object.defineProperty(exports, "ReplaceOrdersRequest", { enumerable: true, get: function () { return ReplaceOrdersRequest_1.default; } });
var Runner_1 = require("./sport/Runner");
Object.defineProperty(exports, "Runner", { enumerable: true, get: function () { return Runner_1.default; } });
var RunnerCatalog_1 = require("./sport/RunnerCatalog");
Object.defineProperty(exports, "RunnerCatalog", { enumerable: true, get: function () { return RunnerCatalog_1.default; } });
var RunnerId_1 = require("./sport/RunnerId");
Object.defineProperty(exports, "RunnerId", { enumerable: true, get: function () { return RunnerId_1.default; } });
var RunnerProfitAndLoss_1 = require("./sport/RunnerProfitAndLoss");
Object.defineProperty(exports, "RunnerProfitAndLoss", { enumerable: true, get: function () { return RunnerProfitAndLoss_1.default; } });
var SetDefaultExposureLimitForMarketGroupsRequest_1 = require("./sport/SetDefaultExposureLimitForMarketGroupsRequest");
Object.defineProperty(exports, "SetDefaultExposureLimitForMarketGroupsRequest", { enumerable: true, get: function () { return SetDefaultExposureLimitForMarketGroupsRequest_1.default; } });
var SetDefaultExposureLimitForMarketGroupsResponse_1 = require("./sport/SetDefaultExposureLimitForMarketGroupsResponse");
Object.defineProperty(exports, "SetDefaultExposureLimitForMarketGroupsResponse", { enumerable: true, get: function () { return SetDefaultExposureLimitForMarketGroupsResponse_1.default; } });
var SetExposureLimitForMarketGroupRequest_1 = require("./sport/SetExposureLimitForMarketGroupRequest");
Object.defineProperty(exports, "SetExposureLimitForMarketGroupRequest", { enumerable: true, get: function () { return SetExposureLimitForMarketGroupRequest_1.default; } });
var SetExposureLimitForMarketGroupResponse_1 = require("./sport/SetExposureLimitForMarketGroupResponse");
Object.defineProperty(exports, "SetExposureLimitForMarketGroupResponse", { enumerable: true, get: function () { return SetExposureLimitForMarketGroupResponse_1.default; } });
var StartingPrices_1 = require("./sport/StartingPrices");
Object.defineProperty(exports, "StartingPrices", { enumerable: true, get: function () { return StartingPrices_1.default; } });
var TimeRangeResult_1 = require("./sport/TimeRangeResult");
Object.defineProperty(exports, "TimeRangeResult", { enumerable: true, get: function () { return TimeRangeResult_1.default; } });
var UnblockMarketGroupRequest_1 = require("./sport/UnblockMarketGroupRequest");
Object.defineProperty(exports, "UnblockMarketGroupRequest", { enumerable: true, get: function () { return UnblockMarketGroupRequest_1.default; } });
var UnblockMarketGroupResponse_1 = require("./sport/UnblockMarketGroupResponse");
Object.defineProperty(exports, "UnblockMarketGroupResponse", { enumerable: true, get: function () { return UnblockMarketGroupResponse_1.default; } });
var UpdateExecutionReport_1 = require("./sport/UpdateExecutionReport");
Object.defineProperty(exports, "UpdateExecutionReport", { enumerable: true, get: function () { return UpdateExecutionReport_1.default; } });
var UpdateInstruction_1 = require("./sport/UpdateInstruction");
Object.defineProperty(exports, "UpdateInstruction", { enumerable: true, get: function () { return UpdateInstruction_1.default; } });
var UpdateInstructionReport_1 = require("./sport/UpdateInstructionReport");
Object.defineProperty(exports, "UpdateInstructionReport", { enumerable: true, get: function () { return UpdateInstructionReport_1.default; } });
var UpdateOrdersRequest_1 = require("./sport/UpdateOrdersRequest");
Object.defineProperty(exports, "UpdateOrdersRequest", { enumerable: true, get: function () { return UpdateOrdersRequest_1.default; } });
var VenueResult_1 = require("./sport/VenueResult");
Object.defineProperty(exports, "VenueResult", { enumerable: true, get: function () { return VenueResult_1.default; } });
var BetStatus_1 = require("./sport/enum/BetStatus");
Object.defineProperty(exports, "BetStatus", { enumerable: true, get: function () { return BetStatus_1.default; } });
var BetTargetType_1 = require("./sport/enum/BetTargetType");
Object.defineProperty(exports, "BetTargetType", { enumerable: true, get: function () { return BetTargetType_1.default; } });
var ExecutionReportErrorCode_1 = require("./sport/enum/ExecutionReportErrorCode");
Object.defineProperty(exports, "ExecutionReportErrorCode", { enumerable: true, get: function () { return ExecutionReportErrorCode_1.default; } });
var ExecutionReportStatus_1 = require("./sport/enum/ExecutionReportStatus");
Object.defineProperty(exports, "ExecutionReportStatus", { enumerable: true, get: function () { return ExecutionReportStatus_1.default; } });
var GroupBy_1 = require("./sport/enum/GroupBy");
Object.defineProperty(exports, "GroupBy", { enumerable: true, get: function () { return GroupBy_1.default; } });
var InstructionReportErrorCode_1 = require("./sport/enum/InstructionReportErrorCode");
Object.defineProperty(exports, "InstructionReportErrorCode", { enumerable: true, get: function () { return InstructionReportErrorCode_1.default; } });
var InstructionReportStatus_1 = require("./sport/enum/InstructionReportStatus");
Object.defineProperty(exports, "InstructionReportStatus", { enumerable: true, get: function () { return InstructionReportStatus_1.default; } });
var LimitBreachActionType_1 = require("./sport/enum/LimitBreachActionType");
Object.defineProperty(exports, "LimitBreachActionType", { enumerable: true, get: function () { return LimitBreachActionType_1.default; } });
var MarketBettingType_1 = require("./sport/enum/MarketBettingType");
Object.defineProperty(exports, "MarketBettingType", { enumerable: true, get: function () { return MarketBettingType_1.default; } });
var MarketGroupType_1 = require("./sport/enum/MarketGroupType");
Object.defineProperty(exports, "MarketGroupType", { enumerable: true, get: function () { return MarketGroupType_1.default; } });
var MarketProjection_1 = require("./sport/enum/MarketProjection");
Object.defineProperty(exports, "MarketProjection", { enumerable: true, get: function () { return MarketProjection_1.default; } });
var MarketSort_1 = require("./sport/enum/MarketSort");
Object.defineProperty(exports, "MarketSort", { enumerable: true, get: function () { return MarketSort_1.default; } });
var MarketStatus_1 = require("./sport/enum/MarketStatus");
Object.defineProperty(exports, "MarketStatus", { enumerable: true, get: function () { return MarketStatus_1.default; } });
var MatchProjection_1 = require("./sport/enum/MatchProjection");
Object.defineProperty(exports, "MatchProjection", { enumerable: true, get: function () { return MatchProjection_1.default; } });
var OrderBy_1 = require("./sport/enum/OrderBy");
Object.defineProperty(exports, "OrderBy", { enumerable: true, get: function () { return OrderBy_1.default; } });
var OrderProjection_1 = require("./sport/enum/OrderProjection");
Object.defineProperty(exports, "OrderProjection", { enumerable: true, get: function () { return OrderProjection_1.default; } });
var OrderStatus_1 = require("./sport/enum/OrderStatus");
Object.defineProperty(exports, "OrderStatus", { enumerable: true, get: function () { return OrderStatus_1.default; } });
var OrderType_1 = require("./sport/enum/OrderType");
Object.defineProperty(exports, "OrderType", { enumerable: true, get: function () { return OrderType_1.default; } });
var PersistenceType_1 = require("./sport/enum/PersistenceType");
Object.defineProperty(exports, "PersistenceType", { enumerable: true, get: function () { return PersistenceType_1.default; } });
var PriceData_1 = require("./sport/enum/PriceData");
Object.defineProperty(exports, "PriceData", { enumerable: true, get: function () { return PriceData_1.default; } });
var PriceLadderType_1 = require("./sport/enum/PriceLadderType");
Object.defineProperty(exports, "PriceLadderType", { enumerable: true, get: function () { return PriceLadderType_1.default; } });
var RollupModel_1 = require("./sport/enum/RollupModel");
Object.defineProperty(exports, "RollupModel", { enumerable: true, get: function () { return RollupModel_1.default; } });
var RunnerStatus_1 = require("./sport/enum/RunnerStatus");
Object.defineProperty(exports, "RunnerStatus", { enumerable: true, get: function () { return RunnerStatus_1.default; } });
var Side_1 = require("./sport/enum/Side");
Object.defineProperty(exports, "Side", { enumerable: true, get: function () { return Side_1.default; } });
var SortDir_1 = require("./sport/enum/SortDir");
Object.defineProperty(exports, "SortDir", { enumerable: true, get: function () { return SortDir_1.default; } });
var TimeGranularity_1 = require("./sport/enum/TimeGranularity");
Object.defineProperty(exports, "TimeGranularity", { enumerable: true, get: function () { return TimeGranularity_1.default; } });
var TimeInForce_1 = require("./sport/enum/TimeInForce");
Object.defineProperty(exports, "TimeInForce", { enumerable: true, get: function () { return TimeInForce_1.default; } });
var ExchangeApi_1 = require("./ExchangeApi");
Object.defineProperty(exports, "ExchangeApi", { enumerable: true, get: function () { return ExchangeApi_1.default; } });
Object.defineProperty(exports, "LoginEndPoint", { enumerable: true, get: function () { return ExchangeApi_1.LoginEndPoint; } });
//# sourceMappingURL=index.js.map