/**
 * Copyright 2018 Colin Doig.  Distributed under the MIT license.
 */
import JsonMember from '../JsonMember';
import OrderStatus from '../sport/enum/OrderStatus';
import OrderType from '../sport/enum/OrderType';
import PersistenceType from '../sport/enum/PersistenceType';
import Side from '../sport/enum/Side';
import PriceSize from '../sport/PriceSize';
export default class CurrentOrderSummary extends JsonMember {
    private betId;
    private marketId;
    private selectionId;
    private handicap;
    private priceSize;
    private bspLiability;
    private side;
    private status;
    private persistenceType;
    private orderType;
    private placedDate;
    private matchedDate;
    private averagePriceMatched;
    private sizeMatched;
    private sizeRemaining;
    private sizeLapsed;
    private sizeCancelled;
    private sizeVoided;
    private regulatorAuthCode;
    private regulatorCode;
    private customerOrderRef;
    private customerStrategyRef;
    constructor(betId?: string, marketId?: string, selectionId?: number | null, handicap?: number | null, priceSize?: PriceSize, bspLiability?: number | null, side?: Side, status?: OrderStatus, persistenceType?: PersistenceType, orderType?: OrderType, placedDate?: Date | null, matchedDate?: Date | null, averagePriceMatched?: number | null, sizeMatched?: number | null, sizeRemaining?: number | null, sizeLapsed?: number | null, sizeCancelled?: number | null, sizeVoided?: number | null, regulatorAuthCode?: string, regulatorCode?: string, customerOrderRef?: string, customerStrategyRef?: string);
    fromJson(json: any): void;
    toJson(): any;
    isValid(): boolean;
    getBetId(): string;
    setBetId(betId: string): void;
    getMarketId(): string;
    setMarketId(marketId: string): void;
    getSelectionId(): number | null;
    setSelectionId(selectionId: number | null): void;
    getHandicap(): number | null;
    setHandicap(handicap: number | null): void;
    getPriceSize(): PriceSize;
    setPriceSize(priceSize: PriceSize): void;
    getBspLiability(): number | null;
    setBspLiability(bspLiability: number | null): void;
    getSide(): Side;
    setSide(side: Side): void;
    getStatus(): OrderStatus;
    setStatus(status: OrderStatus): void;
    getPersistenceType(): PersistenceType;
    setPersistenceType(persistenceType: PersistenceType): void;
    getOrderType(): OrderType;
    setOrderType(orderType: OrderType): void;
    getPlacedDate(): Date | null;
    setPlacedDate(placedDate: Date | null): void;
    getMatchedDate(): Date | null;
    setMatchedDate(matchedDate: Date | null): void;
    getAveragePriceMatched(): number | null;
    setAveragePriceMatched(averagePriceMatched: number | null): void;
    getSizeMatched(): number | null;
    setSizeMatched(sizeMatched: number | null): void;
    getSizeRemaining(): number | null;
    setSizeRemaining(sizeRemaining: number | null): void;
    getSizeLapsed(): number | null;
    setSizeLapsed(sizeLapsed: number | null): void;
    getSizeCancelled(): number | null;
    setSizeCancelled(sizeCancelled: number | null): void;
    getSizeVoided(): number | null;
    setSizeVoided(sizeVoided: number | null): void;
    getRegulatorAuthCode(): string;
    setRegulatorAuthCode(regulatorAuthCode: string): void;
    getRegulatorCode(): string;
    setRegulatorCode(regulatorCode: string): void;
    getCustomerOrderRef(): string;
    setCustomerOrderRef(customerOrderRef: string): void;
    getCustomerStrategyRef(): string;
    setCustomerStrategyRef(customerStrategyRef: string): void;
}
